[tool.poetry]
name = "tap-lastfm"
version = "0.1.0"
description = "`tap-lastfm` is a Singer tap for Last.FM, built with the Meltano SDK for Singer Taps."
authors = ["Charles Julian Knight <charles@rabidaudio.com>"]
keywords = [
    "ELT",
    "LastFM",
    "last.fm",
    "audioscrobbler",
]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
requests = "^2.25.1"
singer-sdk = "^0.5.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
tox = "^3.24.4"
flake8 = "^3.9.2"
black = "^22.3.0"
pydocstyle = "^6.1.1"
mypy = "^0.910"
types-requests = "^2.26.1"
isort = "^5.10.1"

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_lastfm"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-lastfm = 'tap_lastfm.tap:TapLastFM.cli'
